from PyQt6 import QtCore, QtGui, QtWidgets

class Formulario2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("ChatBot")
        Dialog.resize(517, 535)
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 521, 541))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.TabChat = QtWidgets.QWidget()
        self.TabChat.setObjectName("TabChat")
        self.Lbltitulo = QtWidgets.QLabel(parent=self.TabChat)
        self.Lbltitulo.setGeometry(QtCore.QRect(20, 10, 491, 51))
        self.Lbltitulo.setObjectName("Lbltitulo")
        self.Btnenviarp = QtWidgets.QPushButton(parent=self.TabChat)
        self.Btnenviarp.setGeometry(QtCore.QRect(340, 450, 81, 31))
        self.Btnenviarp.setStyleSheet("background-color: rgb(0, 170, 255);border-radius:10px;")
        self.Btnenviarp.setObjectName("Btnenviarp")
        self.TxtPregunta = QtWidgets.QLineEdit(parent=self.TabChat)
        self.TxtPregunta.setGeometry(QtCore.QRect(10, 450, 311, 31))
        self.TxtPregunta.setStyleSheet("border-radius:10px;")
        self.TxtPregunta.setObjectName("TxtPregunta")
        self.TxtChatb = QtWidgets.QTextBrowser(parent=self.TabChat)
        self.TxtChatb.setGeometry(QtCore.QRect(10, 60, 481, 381))
        self.TxtChatb.setStyleSheet("border-radius:5px;")
        self.TxtChatb.setObjectName("TxtChatb")
        self.label = QtWidgets.QLabel(parent=self.TabChat)
        self.label.setGeometry(QtCore.QRect(0, -20, 531, 551))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.971591, y2:0.966, stop:0.0227273 rgba(0, 111, 198, 160), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.Lbltitulo.raise_()
        self.Btnenviarp.raise_()
        self.TxtPregunta.raise_()
        self.TxtChatb.raise_()
        self.tabWidget.addTab(self.TabChat, "")
        self.TabHist = QtWidgets.QWidget()
        self.TabHist.setObjectName("TabHist")
        self.CmbFechah = QtWidgets.QComboBox(parent=self.TabHist)
        self.CmbFechah.setGeometry(QtCore.QRect(60, 60, 101, 22))
        self.CmbFechah.setStyleSheet("border-radius:10px;")
        self.CmbFechah.setObjectName("CmbFechah")
        self.Lbltitulo_2 = QtWidgets.QLabel(parent=self.TabHist)
        self.Lbltitulo_2.setGeometry(QtCore.QRect(20, 0, 491, 51))
        self.Lbltitulo_2.setObjectName("Lbltitulo_2")
        self.Lbltitulo_3 = QtWidgets.QLabel(parent=self.TabHist)
        self.Lbltitulo_3.setGeometry(QtCore.QRect(10, 50, 51, 41))
        self.Lbltitulo_3.setObjectName("Lbltitulo_3")
        self.TxtHistorial = QtWidgets.QTextBrowser(parent=self.TabHist)
        self.TxtHistorial.setGeometry(QtCore.QRect(10, 90, 481, 381))
        self.TxtHistorial.setObjectName("TxtHistorial")
        self.BtnConsultar = QtWidgets.QPushButton(parent=self.TabHist)
        self.BtnConsultar.setGeometry(QtCore.QRect(410, 60, 81, 21))
        self.BtnConsultar.setStyleSheet("background-color: rgb(0, 170, 255);border-radius:10px;")
        self.BtnConsultar.setObjectName("BtnConsultar")
        self.Lbltitulo_4 = QtWidgets.QLabel(parent=self.TabHist)
        self.Lbltitulo_4.setGeometry(QtCore.QRect(170, 50, 71, 41))
        self.Lbltitulo_4.setObjectName("Lbltitulo_4")
        self.label_2 = QtWidgets.QLabel(parent=self.TabHist)
        self.label_2.setGeometry(QtCore.QRect(0, -40, 541, 581))
        self.label_2.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.971591, y2:0.966, stop:0.0227273 rgba(0, 111, 198, 160), stop:1 rgba(255, 255, 255, 255));")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.CmbNombre = QtWidgets.QComboBox(parent=self.TabHist)
        self.CmbNombre.setGeometry(QtCore.QRect(240, 60, 161, 22))
        self.CmbNombre.setStyleSheet("border-radius:10px;")
        self.CmbNombre.setObjectName("CmbNombre")
        self.label_2.raise_()
        self.CmbFechah.raise_()
        self.Lbltitulo_2.raise_()
        self.Lbltitulo_3.raise_()
        self.TxtHistorial.raise_()
        self.BtnConsultar.raise_()
        self.Lbltitulo_4.raise_()
        self.CmbNombre.raise_()
        self.tabWidget.addTab(self.TabHist, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Lbltitulo.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:22pt;\">Hola! Soy DENDE tu asistente virtual,</span></p></body></html>"))
        self.Btnenviarp.setText(_translate("Dialog", "ENVIAR "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabChat), _translate("Dialog", "Chat Bot"))
        self.Lbltitulo_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:16pt;\">Hola! Selecciona la fecha del chat a consultar,</span></p></body></html>"))
        self.Lbltitulo_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Fecha:</span></p></body></html>"))
        self.BtnConsultar.setText(_translate("Dialog", "Consultar"))
        self.Lbltitulo_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Nombre:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabHist), _translate("Dialog", "Historial"))

