from PyQt6 import QtCore, QtGui, QtWidgets


class Formulario1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("ChatBot")
        Dialog.resize(513, 494)
        Dialog.setStyleSheet("QDialog#principaldialog{\n"
        "background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.971591, y2:0.966, stop:0.0227273 rgba(0, 111, 198, 160), stop:1 rgba(255, 255, 255, 255));}\n"
        "")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 300, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 340, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Btnenviar = QtWidgets.QPushButton(parent=Dialog)
        self.Btnenviar.setGeometry(QtCore.QRect(280, 380, 91, 31))
        self.Btnenviar.setStyleSheet("background-color: rgb(0, 170, 255);border-radius:10px;")
        self.Btnenviar.setObjectName("Btnenviar")
        self.TxtEmail = QtWidgets.QLineEdit(parent=Dialog)
        self.TxtEmail.setGeometry(QtCore.QRect(160, 300, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.TxtEmail.setFont(font)
        self.TxtEmail.setStyleSheet("border-radius:10px;")
        self.TxtEmail.setObjectName("TxtEmail")
        self.Lbltitulo = QtWidgets.QLabel(parent=Dialog)
        self.Lbltitulo.setGeometry(QtCore.QRect(30, 10, 491, 91))
        self.Lbltitulo.setObjectName("Lbltitulo")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 220, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.TxtNombre = QtWidgets.QLineEdit(parent=Dialog)
        self.TxtNombre.setGeometry(QtCore.QRect(160, 260, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.TxtNombre.setFont(font)
        self.TxtNombre.setStyleSheet("border-radius:10px;")
        self.TxtNombre.setObjectName("TxtNombre")
        self.TxtTel = QtWidgets.QLineEdit(parent=Dialog)
        self.TxtTel.setGeometry(QtCore.QRect(160, 340, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.TxtTel.setFont(font)
        self.TxtTel.setStyleSheet("border-radius:10px;")
        self.TxtTel.setObjectName("TxtTel")
        self.CmbTipodoc = QtWidgets.QComboBox(parent=Dialog)
        self.CmbTipodoc.setGeometry(QtCore.QRect(160, 180, 61, 22))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.CmbTipodoc.setFont(font)
        self.CmbTipodoc.setStyleSheet("border-radius:10px;")
        self.CmbTipodoc.setObjectName("CmbTipodoc")
        self.CmbTipodoc.addItem("")
        self.CmbTipodoc.addItem("")
        self.CmbTipodoc.addItem("")
        self.CmbTipodoc.addItem("")
        self.CmbTipodoc.addItem("")
        self.CmbTipodoc.addItem("")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.TxtNumdoc = QtWidgets.QLineEdit(parent=Dialog)
        self.TxtNumdoc.setGeometry(QtCore.QRect(160, 220, 311, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.TxtNumdoc.setFont(font)
        self.TxtNumdoc.setStyleSheet("border-radius:10px;")
        self.TxtNumdoc.setObjectName("TxtNumdoc")
        self.Lbltitulo_2 = QtWidgets.QLabel(parent=Dialog)
        self.Lbltitulo_2.setGeometry(QtCore.QRect(30, 80, 481, 51))
        self.Lbltitulo_2.setObjectName("Lbltitulo_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 511, 501))
        self.label.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0.971591, y2:0.966, stop:0.0227273 rgba(0, 111, 198, 160), stop:1 rgba(255, 255, 255, 255));")
        self.label.setText("")
        self.label.setObjectName("label")
        self.BtnSalir = QtWidgets.QPushButton(parent=Dialog)
        self.BtnSalir.setGeometry(QtCore.QRect(390, 380, 91, 31))
        self.BtnSalir.setStyleSheet("background-color: rgb(0, 170, 255);border-radius:10px;")
        self.BtnSalir.setObjectName("BtnSalir")
        self.label.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.Btnenviar.raise_()
        self.TxtEmail.raise_()
        self.Lbltitulo.raise_()
        self.label_4.raise_()
        self.TxtNombre.raise_()
        self.TxtTel.raise_()
        self.CmbTipodoc.raise_()
        self.label_5.raise_()
        self.TxtNumdoc.raise_()
        self.Lbltitulo_2.raise_()
        self.label_3.raise_()
        self.BtnSalir.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_6.setText(_translate("Dialog", "Email:"))
        self.label_7.setText(_translate("Dialog", "Telefono:"))
        self.Btnenviar.setText(_translate("Dialog", "ENVIAR "))
        self.Lbltitulo.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:22pt;\">Hola! Soy DENDE tu asistente virtual,</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Numero documento:"))
        self.CmbTipodoc.setItemText(0, _translate("Dialog", "TI"))
        self.CmbTipodoc.setItemText(1, _translate("Dialog", "CC"))
        self.CmbTipodoc.setItemText(2, _translate("Dialog", "CE"))
        self.CmbTipodoc.setItemText(3, _translate("Dialog", "PS"))
        self.CmbTipodoc.setItemText(4, _translate("Dialog", "PT"))
        self.CmbTipodoc.setItemText(5, _translate("Dialog", "PE"))
        self.label_5.setText(_translate("Dialog", "Nombre Completo:"))
        self.Lbltitulo_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Por favor completa la siguente informacion para ser atendido.</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Tipo de documento:"))
        self.BtnSalir.setText(_translate("Dialog", "SALIR"))